### PR TITLE
Added strong name

### PR DESCRIPTION
**Pull request by Scordo**

### CODE REVIEW

**Comment by uranium62** [comment]
Done: https://www.nuget.org/packages/Standart.Hash.xxHash.Signed

I did it manually. Please create a pull request and add steps to the release.yml (Github actions). Do it all automatically

**Comment by uranium62** [comment]
And I want to have a version both signed and unsigned

**Comment by JensAtQuanos** [comment]
> Done: https://www.nuget.org/packages/Standart.Hash.xxHash.Signed
> 
> I did it manually. Please create a pull request and add steps to the release.yml (Github actions). Do it all automatically

Your signing-branch does not contain the *.snk file. So I cant do what you want ;-)

**Comment by Scordo** [comment]
> Done: https://www.nuget.org/packages/Standart.Hash.xxHash.Signed
> 
> I did it manually. Please create a pull request and add steps to the release.yml (Github actions). Do it all automatically

Your signing-branch does not contain the *.snk file. So I cant do what you want ;-)

**Pull request closed without merging**
